### ISSUE TITLE
Logical operator precedence wrong ?

### ISSUE THREAD

**Issue by apnadkarni** [auriocus/VecTcl#3]
Seems to be the precedence of && and || is incorrect (where incorrect means inconsistent with other languages including Tcl's expr)
```
% A = 0
{0}
% B = 1
{1}
% C = 1
{1}
% A && B || C
{0}
% B || C && A
{0}
```
Compare with
```
% set a 0 ; set b 1 ; set c 1
1
% expr {$a && $b || $c}
1
% expr {$b || $c && $a}
1
```

**Comment by auriocus** [comment]
Thank you for reporting this problem. Indeed the precedence is swapped, which can be proven by inspecting the compiler output:
 
    % vectcl::compile { A && B || C }
    upvar 1 A A
    upvar 1 B B
    upvar 1 C C
    numarray::&& [set A] [numarray::|| [set B] [set C]]


It seems to be an error in the grammar.

**Comment by auriocus** [comment]
Fixed in HEAD
