### ISSUE TITLE
drem is deprecated on macOS 10.9

### ISSUE THREAD

**Issue by sl1200mk2** [auriocus/VecTcl#7]
Hi,
I would like to try vecTcl but when I compile it on macOS 10.9 I get this warning:
./generic/f2c_mathlib.h:423:6: warning: 'drem' is deprecated: first deprecated
      in OS X 10.9 [-Wdeprecated-declarations]
        z = drem(xa = *x, ya);

best regards,
nicolas

**Comment by sl1200mk2** [comment]
remainder() instead of drem() in f2c_mathlib.h fixes the warnings

++

**Comment by auriocus** [comment]
Thank you. This is code coming originally from f2c, the fortran to C compiler. I will check if drem is generally deprecated, otherwise, it's just a warning

**Comment by auriocus** [comment]
Fixed
