### ISSUE TITLE
Cannot use "strings" inside a vproc (?)

### ISSUE THREAD

**Issue by bsdooby** [auriocus/VecTcl#8]
Example: vexpr { DBG = "message"; puts($DBG)}

this results in a parse error message: Error: Parse error in line 1:7

**Comment by auriocus** [comment]
This is correct; at the moment the parser in VecTcl does not support strings. Apart from that, there is another error in the code, the "$" sign is not supported or needed for dereferencing. What works is variables previously assigned with a string, i.e. 

set DBG "message"
vexpr { puts(DBG) }

**Comment by bsdooby** [comment]
Ah yes, thank you for the clarification. Keep up the good work with VecTcl (any future plans?).
