### ISSUE TITLE
complex128 compile error

### ISSUE THREAD

**Issue by tec-lab** [auriocus/VecTcl#9]
Based on the this commit: ac31bb75b214aa96097def3b26b41fc94340fc76

There are compile errors using the struct complex128. They can be fixed the following:

/vectcl/generic/vectcl.h, line 79 should be:
`NumArray_Complex Complex128;`

external/vectcl/generic/vectclapi.c, three places should be:
`value.value.Complex128` instead of `value.value.Complex`

**Comment by auriocus** [comment]
vectcl.h is correct in the repo, but wrong in the template vectcl.tcl.h. https://github.com/auriocus/VecTcl/blob/ac31bb75b214aa96097def3b26b41fc94340fc76/generic/vectcl.h#L79
It shouldn't normally be recreated from the template, but it is a bug indeed. vectclapi.c looks correct to me, though:
https://github.com/auriocus/VecTcl/blob/ac31bb75b214aa96097def3b26b41fc94340fc76/generic/vectclapi.c#L828
Please check your checkout.

**Comment by tombert-zz** [comment]
I did a fresh clone and I am on the latest commit ac31bb75b214aa96097def3b26b41fc94340fc76, still the bug is here.

**Comment by auriocus** [comment]
Please try again. It was still wrong in the template, and for some reason the template file must have been expanded in your case - probably the time stamps are not preserved correctly in the git checkout.

**Comment by tombert-zz** [comment]
Now it compiles clean. Thx!
